### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isModified' of undefined

### ISSUE THREAD

**Issue by lionel-rigoux** [lionel-rigoux/pandemic-plugin#1]
Pandemic throws an error when trying to publish without any active editor.

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.11.6
**Thrown From**: [pandemic](https://github.com/lionel-rigoux/pandemic-plugin) package 0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'isModified' of undefined

```
At /Users/lrigoux/.atom/packages/pandemic/lib/pandemic.js:34

TypeError: Cannot read property 'isModified' of undefined
    at Object.publish (/packages/pandemic/lib/pandemic.js:34:19)
    at HTMLElement.pandemicPublish (/packages/pandemic/lib/pandemic.js:16:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  3x -0:35.7.0 core:close (input.hidden-input)
     -0:33 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:29.8.0 pandemic:publish (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atomic-chrome 0.3.3 
autocomplete-bibtex 1.2.1 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
intentions 1.1.5 
language-markdown 0.25.1 
language-matlab 0.2.1 
language-pug 0.0.22 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.5 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
pandemic 0.3.2 
preview 0.17.0 
script 3.17.3 
split-diff 1.5.2 
table-editor 0.2.2 
tidy-markdown 3.0.1 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs-snippets 0.1.0 
vuejs2-snippets 0.15.0 
wordcount 2.10.4 
Zen 0.18.0 
```

**Comment by lionel-rigoux** [comment]
fixed by #6bae0477decc2bec131d63f94410120a4e695bc8
